# Generated by Django 3.0.8 on 2020-07-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200726_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='on_entry',
            new_name='entry',
        ),
    ]
