# Generated by Django 3.0.8 on 2020-07-30 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20200726_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
