# Generated by Django 3.0.8 on 2020-08-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
